---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: "Setup local Postgre DB"
      command: |
        docker run --name postgres --detach --publish 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust --mount type=tmpfs,destination=/var/lib/postgresql/data postgres

    